clone_folder: c:\users\appveyor\certcheck
environment:
  GOPATH: c:\gopath
  matrix:
  - GOOS: windows
    GOARCH: 386
  - GOOS: windows
    GOARCH: amd64
  - GOOS: linux
    GOARCH: 386
  - GOOS: linux
    GOARCH: amd64
install:
  - go get gopkg.in/yaml.v2
  - set PATH=%PATH%;%GOPATH%\bin
before_build:
  - set GOOS=%_GOOS%
  - set GOARCH=%_GOARCH%
build_script:
  - dep ensure
  - go build
