clone_folder: c:\users\appveyor\certcheck
environment:
  GOPATH: c:\gopath
  matrix:
  - GOOS: windows
    GOARCH: 386
    FILENAME: certcheck_windows_386.exe
  - GOOS: windows
    GOARCH: amd64
    FILENAME: certcheck_windows_amd64.exe
  - GOOS: linux
    GOARCH: 386
    FILENAME: certcheck_linux_386
  - GOOS: linux
    GOARCH: amd64
    FILENAME: certcheck_linux_amd64
install:
  - nuget restore
  - go version
  - go env
  - set PATH=%PATH%;%GOPATH%\bin
  - go get gopkg.in/yaml.v2
  - ps: |
      $(Get-Content "c:\users\appveyor\certcheck\certcheck.go") -replace "{version}","1.2.3" -replace "${revision}","${env:APPVEYOR_BUILD_VERSION}" > "c:\users\appveyor\certcheck\certcheck.go"
before_build:
  - set GOOS=%_GOOS%
  - set GOARCH=%_GOARCH%
build_script:
  - go build -o FILENAME
artifacts:
  - path: 'c:\users\appveyor\certcheck\certcheck_windows_386.exe'
  - path: 'c:\users\appveyor\certcheck\certcheck_windows_amd64.exe'
  - path: 'c:\users\appveyor\certcheck\certcheck_linux_386'
  - path: 'c:\users\appveyor\certcheck\certcheck_linux_amd64'
