clone_folder: c:\users\appveyor\certcheck
environment:
  GOPATH: c:\gopath
  matrix:
  - GOOS: windows
    GOARCH: 386
  - GOOS: windows
    GOARCH: amd64
  - GOOS: linux
    GOARCH: 386
  - GOOS: linux
    GOARCH: amd64
build_script:
  - set PATH=%PATH%;%GOPATH%\bin
  - go build github.com/golang/dep/dep/cmd/dep
  - for /f "" %%G in ('go list github.com/golang/dep/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
  - dep ensure
  - go build
