version: 1.2.3.{build}
image: Visual Studio 2022
clone_folder: c:\certcheck
stack: go 1.24
environment:
  GO111MODULE: on
  matrix:
  - GOOS: windows
    GOARCH: amd64
    FILENAME: certcheck_windows_amd64.exe
  - GOOS: windows
    GOARCH: 386
    FILENAME: certcheck_windows_386.exe
  - GOOS: linux
    GOARCH: amd64
    FILENAME: certcheck_linux_amd64
  - GOOS: linux
    GOARCH: 386
    FILENAME: certcheck_linux_386
install:
  - go version
  - go env
  - cd c:\certcheck
  - go mod download
build_script:
  - cd c:\certcheck
  - go build -trimpath -ldflags "-s -w -X main.Version=%APPVEYOR_BUILD_VERSION% -X main.Revision=%APPVEYOR_REPO_COMMIT%" -o %FILENAME%
artifacts:
  - path: '.\certcheck_*'
