clone_folder: c:\certcheck
environment:
  GOPATH: c:\gopath
  matrix:
  - GOOS: windows
    GOARCH: amd64
    FILENAME: c:\certcheck\certcheck_windows_amd64.exe
#  - GOOS: windows
#    GOARCH: 386
#    FILENAME: c:\certcheck\certcheck_windows_386.exe
#  - GOOS: linux
#    GOARCH: amd64
#    FILENAME: c:\certcheck\certcheck_linux_amd64
#  - GOOS: linux
#    GOARCH: 386
#    FILENAME: c:\certcheck\certcheck_linux_386
install:
  - go version
  - go env
  - set PATH=%PATH%;%GOPATH%\bin
  - go get gopkg.in/yaml.v2
  - ps: |
      $(Get-Content "c:\certcheck\certcheck.go" -Raw).Replace("{version}","1.2.3").Replace("{revision}","${env:APPVEYOR_BUILD_VERSION}") | Out-File "c:\certcheck\certcheck.go";
      cat c:\certcheck\certcheck.go
before_build:
  - set GOOS=%_GOOS%
  - set GOARCH=%_GOARCH%
build_script:
  - echo %FILENAME%
  - go build c:\certcheck\certcheck.go -o %FILENAME%
artifacts:
  - path: 'c:\certcheck\certcheck_windows_386.exe'
  - path: 'c:\certcheck\certcheck_windows_amd64.exe'
  - path: 'c:\certcheck\certcheck_linux_386'
  - path: 'c:\certcheck\certcheck_linux_amd64'
